import type { MedicationTemplate } from '../types';

export const MEDICATION_LIBRARY: MedicationTemplate[] = [
  {
    id: 'semaglutide',
    name: 'Semaglutide',
    brand: 'Ozempic / Wegovy / Rybelsus',
    activeIngredient: 'Semaglutide',
    dosageOptions: [0.25, 0.5, 1, 1.7, 2, 2.4],
    unit: 'mg',
    frequency: 'weekly',
    halfLifeHours: 168,
    color: '#14b8a6',
  },
  {
    id: 'tirzepatide',
    name: 'Tirzepatide',
    brand: 'Mounjaro / Zepbound',
    activeIngredient: 'Tirzepatide',
    dosageOptions: [2.5, 5, 7.5, 10, 12.5, 15],
    unit: 'mg',
    frequency: 'weekly',
    halfLifeHours: 120,
    color: '#f59e0b',
  },
  {
    id: 'liraglutide',
    name: 'Liraglutide',
    brand: 'Victoza / Saxenda',
    activeIngredient: 'Liraglutide',
    dosageOptions: [0.6, 1.2, 1.8, 3],
    unit: 'mg',
    frequency: 'daily',
    halfLifeHours: 13,
    color: '#8b5cf6',
  },
  {
    id: 'dulaglutide',
    name: 'Dulaglutide',
    brand: 'Trulicity',
    activeIngredient: 'Dulaglutide',
    dosageOptions: [0.75, 1.5, 3, 4.5],
    unit: 'mg',
    frequency: 'weekly',
    halfLifeHours: 120,
    color: '#ec4899',
  },
  {
    id: 'exenatide',
    name: 'Exenatide',
    brand: 'Byetta',
    activeIngredient: 'Exenatide',
    dosageOptions: [5, 10],
    unit: 'mcg',
    frequency: 'twice-daily',
    halfLifeHours: 2.4,
    color: '#3b82f6',
  },
  {
    id: 'exenatide-er',
    name: 'Exenatide ER',
    brand: 'Bydureon / Bydureon BCise',
    activeIngredient: 'Exenatide ER',
    dosageOptions: [2],
    unit: 'mg',
    frequency: 'weekly',
    halfLifeHours: 336,
    color: '#06b6d4',
  },
  {
    id: 'lixisenatide',
    name: 'Lixisenatide',
    brand: 'Adlyxin',
    activeIngredient: 'Lixisenatide',
    dosageOptions: [10, 20],
    unit: 'mcg',
    frequency: 'daily',
    halfLifeHours: 3,
    color: '#84cc16',
  },
  {
    id: 'retatrutide',
    name: 'Retatrutide',
    brand: 'Zepbound',
    activeIngredient: 'Retatrutide',
    dosageOptions: [1, 2, 4, 8, 12],
    unit: 'mg',
    frequency: 'weekly',
    halfLifeHours: 168,
    color: '#ef4444',
  },
];
